namespace AdvertWebAPI_Restful.Migrations;

// <auto-generated />

using AdvertWebAPI_Restful.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.12")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("AdvertWebAPI_Restful.Model.Advert", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("AdvertText")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("AdvertTitle")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime>("DateAdded")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("Adverts");
            });
#pragma warning restore 612, 618
    }
}
